"""initial

Revision ID: b0b49047523e
Revises: 
Create Date: 2025-04-14 05:30:58.894568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0b49047523e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('abn', sa.String(length=20), nullable=True),
    sa.Column('acn', sa.String(length=20), nullable=True),
    sa.Column('company_type', sa.String(length=50), nullable=True),
    sa.Column('registered_address', sa.Text(), nullable=True),
    sa.Column('qbcc_license_number', sa.String(length=50), nullable=True),
    sa.Column('document_folder', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abn')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('image_filename', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('family_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('tfn', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('abn', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plate', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('vin', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('rego_renewal_date', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('insurance_renewal_date', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('expiry', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('value', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('transfer_fee', sa.Float(), nullable=True))
        batch_op.create_unique_constraint(None, ['plate'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('transfer_fee')
        batch_op.drop_column('value')
        batch_op.drop_column('expiry')
        batch_op.drop_column('insurance_renewal_date')
        batch_op.drop_column('rego_renewal_date')
        batch_op.drop_column('vin')
        batch_op.drop_column('type')
        batch_op.drop_column('plate')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('phone')
        batch_op.drop_column('email')
        batch_op.drop_column('address')
        batch_op.drop_column('abn')
        batch_op.drop_column('tfn')
        batch_op.drop_column('family_name')
        batch_op.drop_column('name')

    op.drop_table('projects')
    op.drop_table('companies')
    # ### end Alembic commands ###
